# Generated by Django 5.2.2 on 2025-06-13 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_firstname', models.CharField(max_length=255, verbose_name='Фамилия покупателя')),
                ('buyer_name', models.CharField(max_length=255, verbose_name='Имя покупателя')),
                ('buyer_surname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество покупателя')),
                ('comment', models.TextField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('delivery_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес доставки')),
                ('delivery_type', models.CharField(choices=[('SH', 'Самовывоз'), ('CR', 'Курьер'), ('PP', 'Пункт выдачи заказов')], default='SH', max_length=2, verbose_name='Тип доставки')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('date_finish', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Pos_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество товара')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Скидка на позицию')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.clothes', verbose_name='Товар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='clothes',
            field=models.ManyToManyField(through='shop.Pos_order', to='shop.clothes', verbose_name='Товар'),
        ),
    ]
